### ISSUE TITLE
TypeError: Member "popcountB" not found or not visible after argument-dependent lookup in struct BitMaps.BitMap storage ref.

### ISSUE THREAD

**Issue by aikoshoemaker** [ctor-lab/ERC1155Delta#6]
got an error while compiling contract with hardhat, how to fix?

**Comment by estarriolvetch** [comment]
Hey @aikoshoemaker !
For some reason, you are missing the `solidiy-bits` dependency.

Also, I just released a new version which no longer needs `solidiy-bits`.
Please try to use `v0.1.0` version!

**Comment by estarriolvetch** [comment]
@aikoshoemaker Let me know if you still encounter the problem
